Convert List to 1D Array
Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array.

Expected Output:

Original List: [12.23, 13.32, 100, 36.32] One-dimensional NumPy array: [ 12.23 13.32 100. 36.32]

In [ ]:
import numpy as np

list_values = [12.23, 13.32, 100, 36.32]

array_1d = np.array(list_values)

print("Original List:", list_values)
print("One-dimensional NumPy array:", array_1d)

Create 3x3 Matrix (2?10)
Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

Expected Output:

[[ 2 3 4] [ 5 6 7] [ 8 9 10]]

In [ ]:
import numpy as np

matrix = np.arange(2, 11).reshape(3, 3)

print(matrix)

In [ ]:
 Null Vector (10) & Update Sixth Value
Write a NumPy program to create a null vector of size 10 and update the sixth value to 11.

[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Update sixth value to 11 [ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [ ]:
import numpy as np

vector = np.zeros(10)
print("Original vector:", vector)

vector[6] = 11
print("Updated vector:", vector)

Array from 12 to 38
Write a NumPy program to create an array with values ranging from 12 to 38.

Expected Output:

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]

In [ ]:
import numpy as np

array = np.arange(12, 38)

print(array)

 Convert Array to Float Type
Write a NumPy program to convert an array to a floating type.

Sample output:

Original array [1, 2, 3, 4]

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])
print("Original array:", arr)

float_arr = arr.astype(float)
print("Array converted to float:", float_arr)

Append Values to Array (Do self-tudy)
Write a NumPy program to append values to the end of an array.

Expected Output:

Original array: [10, 20, 30]

After append values to the end of the array: [10 20 30 40 50 60 70 80 90]

In [ ]:
arr = np.array([10, 20, 30])
print("Original array:", arr)

values_to_append = [40, 50, 60, 70, 80, 90]

new_arr = np.append(arr, values_to_append)
print("After append values to the end of the array:", new_arr)

Array Statistical Functions (Do self-tudy)
Create a random NumPy array of 10 elements and calculate the mean, median, and standard deviation of the array.

In [ ]:
import numpy as np

arr = np.random.randint(0, 101, size=10)

print("Random array:", arr)

Find min and max
Create a 10x10 array with random values and find the minimum and maximum values.



In [ ]:
arr = np.random.randint(0, 101, size=(10, 10))

print("Random 10x10 array:\n", arr)

min_val = np.min(arr)
max_val = np.max(arr)

print("Minimum value:", min_val)
print("Maximum value:", max_val)

Create a 3x3x3 array with random values.

In [ ]:
import numpy as np

array_3d = np.random.rand(3, 3, 3)

print("3x3x3 Random Array:")
print(array_3d)